### PR TITLE
Fix hang issue

### PR DESCRIPTION
**Pull request by ota-meshi**

### CODE REVIEW

**Comment by JounQin** [comment]
@ota-meshi Hi, so https://github.com/un-ts/synckit/pull/101 does not help in this case? Is that possible to be fixed on `synckit`'s side?

**Comment by ota-meshi** [comment]
This issue is not a synckit issue.
I think it's a problem with astrojs/compiler or whatever tool generates that wasm.
astrojs/compiler seems to call process.exit() on error. So the worker suddenly disappears without any notification.
This PR is a change that works around that issue.

**Comment by JounQin** [comment]
Thanks for explanation!

**Comment by JounQin** [comment]
@ota-meshi I'm still wondering if it can be **fixed** on `synckit`'s side, as you fixing here by terminating the worker on `exit`?

**Pull request merged**
